name: Spider Jar Gen CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permissions for build.bat
        run: |
          git update-index --chmod=+x ./build.bat
        shell: bash

      - name: Build with Gradle
        run: ./build.bat ec

      - name: Upload jar as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: custom_spider_jar
          path: |
            ./jar/custom_spider.jar
            ./jar/custom_spider.jar.md5

      - name: Commit and push updated jar
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'update spider jar'
          add: |
            ./jar/custom_spider.jar
            ./jar/custom_spider.jar.md5
